site_name: QIRT Documentation

theme:
  name: "material"
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - toc.integrate
    - navigation.prune
    - navigation.indexes
    - navigation.top
  icon:
    repo: fontawesome/brands/github


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 3

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
  - Welcome to QIRT: index.md
  - Tutorials: 
    - tutorials/index.md
    - 1. Setup: tutorials/setup.md
    - 2. Create a Basic Quantum State: tutorials/create_state.md
    - 3. Create a Basic Quantum Circuit: tutorials/create_circuit.md
    - 4. Applye the Quantum Circuit to the Quantum State: tutorials/apply_circuit.md
    - 5. Measure the Quantum State: tutorials/measurement.md
  - How-To Guides: 
    - how-to-guides/index.md
    - Create Quantum States: how-to-guides/create-quantum-states.md
    - Visualize Quantum States: how-to-guides/visualize-quantum-states.md
    - Quantum Measurement: how-to-guides/quantum-measurement.md
    - Customize Ket Notation: how-to-guides/customize-ket-notation.md
  - Reference: 
    - reference/index.md
    - QuantumState: reference/quantum-state.md
    - QuantumCircuit: reference/quantum-circuit.md

repo_url: https://github.com/Slope86/QIRT

repo_name: Slope86/QIRT

site_url: https://slope86.github.io/QIRT/